package wolt.mybatis.model;

public class RestaurantFood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESTAURANT_FOOD.FOOD_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    private Integer foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESTAURANT_FOOD.RESTAURANT_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    private Integer restaurantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESTAURANT_FOOD.FOOD_ID
     *
     * @return the value of PUBLIC.RESTAURANT_FOOD.FOOD_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESTAURANT_FOOD.FOOD_ID
     *
     * @param foodId the value for PUBLIC.RESTAURANT_FOOD.FOOD_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESTAURANT_FOOD.RESTAURANT_ID
     *
     * @return the value of PUBLIC.RESTAURANT_FOOD.RESTAURANT_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESTAURANT_FOOD.RESTAURANT_ID
     *
     * @param restaurantId the value for PUBLIC.RESTAURANT_FOOD.RESTAURANT_ID
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }
}