package wolt.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import wolt.mybatis.model.Food;

@Mapper
public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    Food selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    List<Food> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOD
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int updateByPrimaryKey(Food record);

    Food findByName(String name);
}