package wolt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import wolt.mybatis.model.Location;

@Mapper
public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    Location selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    List<Location> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LOCATION
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int updateByPrimaryKey(Location record);
}