package wolt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import wolt.mybatis.model.Restaurant;

@Mapper
public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    Restaurant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    List<Restaurant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESTAURANT
     *
     * @mbg.generated Tue May 10 00:52:59 EEST 2022
     */
    int updateByPrimaryKey(Restaurant record);
}